name: main
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: src
        run: dotnet build --configuration Release
      - name: Pack
        working-directory: src
        run: dotnet pack --no-build --configuration Release
      - name: Push NuGet package
        working-directory: src
        run: |
          dotnet nuget push **/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
